### ISSUE TITLE
how to combine the hex files

### ISSUE THREAD

**Issue by K4stor** [ndf-zz/asfv1#3]
I want to use this assembler so I can work completly on OSX.
If I assemble several patches with different program numbers as parameters
How would I combine these to one big file that I can copy to my eeprom.

**Comment by ndf-zz** [comment]
To make a bank file for upload to an eeprom, assemble to binary files then concatenate them to the bank. Something like:

 asfv1 -b prog0.asm prog0.bin ; asfv1 -b prog1.asm prog1.bin ; ...

then 

cat prog[0-7].bin > bank.bin

Alternatively you can use a Makefile and call a program like dd to write each program into the proper position in a bank file. This is the approach I use.

**Comment by ndf-zz** [comment]
See also: https://github.com/ndf-zz/fv1build
