### ISSUE TITLE
What is the workflow for a spin project with multiple effects?

### ISSUE THREAD

**Issue by hhaudio** [ndf-zz/asfv1#8]
Hi, first off, thanks for making this. Been looking for a way to do this on OSX for while. 

This seems to be working for me, but wondering if there's an easy way to compile a hex for multiple programs, like the spin project functionality. That's going to be most of my use cases. Right now it seems like I'd have to copy and paste the hex information to get that.

Please let me know, thanks!

**Comment by ndf-zz** [comment]
Hi thanks for your message, make works quite well for this purpose, see related repositories for some examples:

   - [fv1build](https://github.com/ndf-zz/fv1build)
   - [fv1testing](https://github.com/ndf-zz/fv1testing)

Alternatively, use the binary output with a program number to write each effect into a single bank. For example, if your effects are called 0.asm, 1.asm, .. etc, use:

```
$ asfv1 -p 0 0.asm bank.bin
$ asfv1 -p 1 1.asm bank.bin
...
$ asfv1 -p 7 7.asm bank.bin
```

If you require a hex bank file, use objcopy, eg:

`$ objcopy -I binary -O ihex bank.bin bank.hex`

Or if you don't want to use binary files, you can concatenate hex files generated by asfv1 - by stripping off the intermediate EOF records, something like:

`$ ( grep -h -v '^:00000001FF' ?.hex && echo ':00000001FF' ) > bank.hex`
